### ISSUE TITLE
AttributeError at /users/

### ISSUE THREAD

**Issue by togaPaulo** [umutbozkurt/django-rest-framework-mongoengine#105] opened 2015-05-28 21:28 UTC
try run server from example and i have error:

'UserSerializer' object has no attribute '_include_additional_options'

**Comment by adil-abbasi-10p** [comment] 2015-06-03 07:55
+1 I am having the same issue.

**Comment by togaPaulo** [comment] 2015-07-15 16:26
I use serializers of django-rest-framework for serializer my documents of mongoengine, it works perfect

**Comment by qwiglydee** [comment] 2015-11-01 10:29
duplicate of #110

**Closed by qwiglydee** 2015-11-01 10:29 UTC
Labels: duplicate
